translator:
  type: ollama
  api_key: YOUR-KEY-GOES-HERE
  model: qwen2.5:32b
  restart_container: true
  container_name: ollama
layout:
  type: dit
  device: cuda
ocr:
  type: paddle
  device: cuda
  model_dir: models/paddle-ocr
  det:
    model: ch_PP-OCRv4_det_infer.onnx
    algorithm: DB
  rec:
    model: en_PP-OCRv4_rec_infer.onnx
    algorithm: SVTR_LCNet
    char_dict: en_dict_v4.txt
  cls:
    enabled: false
render:
  type: reportlab # or 'simple'
  font_name: STSong
  font_path: ./fonts/STSong.ttf
  render_mode: INTERLEAVE
multi_thread:
  enable: false
gui:
  database_name: pdf_translator_files.db
  download_folder: download
  translate_folder: translate
